-- MySQL Script generated by MySQL Workbench
-- Wed Jun  7 10:07:08 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_petsaude
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_petsaude
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_petsaude` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_petsaude` ;

-- -----------------------------------------------------
-- Table `db_petsaude`.`_prisma_migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_petsaude`.`_prisma_migrations` (
  `id` VARCHAR(36) NOT NULL,
  `checksum` VARCHAR(64) NOT NULL,
  `finished_at` DATETIME(3) NULL DEFAULT NULL,
  `migration_name` VARCHAR(255) NOT NULL,
  `logs` TEXT NULL DEFAULT NULL,
  `rolled_back_at` DATETIME(3) NULL DEFAULT NULL,
  `started_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `applied_steps_count` INT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_petsaude`.`tbl_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_petsaude`.`tbl_address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(10) NOT NULL,
  `complement` VARCHAR(5) NULL DEFAULT NULL,
  `number` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_petsaude`.`tbl_client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_petsaude`.`tbl_client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `person_name` VARCHAR(100) NOT NULL,
  `user_name` VARCHAR(50) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `rg` VARCHAR(14) NULL DEFAULT NULL,
  `profile_photo` VARCHAR(191) NULL DEFAULT NULL,
  `profile_banner_photo` VARCHAR(191) NULL DEFAULT NULL,
  `email` VARCHAR(256) NOT NULL,
  `password` VARCHAR(191) NOT NULL,
  `biography` VARCHAR(1000) NULL DEFAULT NULL,
  `address_id` INT NOT NULL,
  `cellphone_number` VARCHAR(15) NOT NULL,
  `is_vet` TINYINT(1) NOT NULL DEFAULT '0',
  `phone_number` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tbl_client_cpf_key` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `tbl_client_email_key` (`email` ASC) VISIBLE,
  UNIQUE INDEX `tbl_client_address_id_key` (`address_id` ASC) VISIBLE,
  UNIQUE INDEX `tbl_client_rg_key` (`rg` ASC) VISIBLE,
  CONSTRAINT `tbl_client_address_id_fkey`
    FOREIGN KEY (`address_id`)
    REFERENCES `db_petsaude`.`tbl_address` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_petsaude`.`tbl_pet_specie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_petsaude`.`tbl_pet_specie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TINYTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_petsaude`.`tbl_pet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_petsaude`.`tbl_pet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `birth_date` DATE NOT NULL,
  `photo` VARCHAR(191) NULL DEFAULT NULL,
  `microship` TINYINT(1) NOT NULL,
  `pet_specie_id` INT NOT NULL,
  `owner_id` INT NOT NULL,
  `pet_gender` ENUM('M', 'F') NOT NULL,
  `pet_size` ENUM('BIG', 'MEDIUM', 'SMALL') NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `tbl_pet_pet_specie_id_fkey` (`pet_specie_id` ASC) VISIBLE,
  INDEX `tbl_pet_owner_id_fkey` (`owner_id` ASC) VISIBLE,
  CONSTRAINT `tbl_pet_owner_id_fkey`
    FOREIGN KEY (`owner_id`)
    REFERENCES `db_petsaude`.`tbl_client` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `tbl_pet_pet_specie_id_fkey`
    FOREIGN KEY (`pet_specie_id`)
    REFERENCES `db_petsaude`.`tbl_pet_specie` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_petsaude`.`tbl_veterinary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_petsaude`.`tbl_veterinary` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `person_name` VARCHAR(100) NOT NULL,
  `user_name` VARCHAR(50) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `rg` VARCHAR(13) NULL DEFAULT NULL,
  `profile_photo` VARCHAR(191) NULL DEFAULT NULL,
  `profile_banner_photo` VARCHAR(191) NULL DEFAULT NULL,
  `email` VARCHAR(256) NOT NULL,
  `password` VARCHAR(191) NOT NULL,
  `occupation_area` VARCHAR(50) NOT NULL,
  `formation` VARCHAR(30) NOT NULL,
  `institution` VARCHAR(100) NOT NULL,
  `crmv` VARCHAR(6) NOT NULL,
  `formation_date` DATE NOT NULL,
  `start_acting_date` DATE NOT NULL,
  `address_id` INT NOT NULL,
  `isVet` TINYINT(1) NOT NULL DEFAULT '1',
  `biography` VARCHAR(1000) NULL DEFAULT NULL,
  `cellphone_number` VARCHAR(15) NOT NULL,
  `phone_number` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tbl_veterinary_cpf_key` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `tbl_veterinary_email_key` (`email` ASC) VISIBLE,
  UNIQUE INDEX `tbl_veterinary_crmv_key` (`crmv` ASC) VISIBLE,
  UNIQUE INDEX `tbl_veterinary_address_id_key` (`address_id` ASC) VISIBLE,
  UNIQUE INDEX `tbl_veterinary_rg_key` (`rg` ASC) VISIBLE,
  CONSTRAINT `tbl_veterinary_address_id_fkey`
    FOREIGN KEY (`address_id`)
    REFERENCES `db_petsaude`.`tbl_address` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_petsaude`.`tbl_appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_petsaude`.`tbl_appointment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(1000) NOT NULL,
  `status` ENUM('CONCLUDED', 'SCHEDULED', 'WAITING_CONFIRMATION', 'CANCELED', 'DECLINED') NOT NULL DEFAULT 'WAITING_CONFIRMATION',
  `date` DATE NOT NULL,
  `starts_at` TIME NOT NULL,
  `client_id` INT NOT NULL,
  `veterinary_id` INT NOT NULL,
  `pet_id` INT NOT NULL,
  `duration` INT NULL DEFAULT NULL,
  `price` DECIMAL(65,30) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `tbl_appointment_client_id_fkey` (`client_id` ASC) VISIBLE,
  INDEX `tbl_appointment_veterinary_id_fkey` (`veterinary_id` ASC) VISIBLE,
  INDEX `tbl_appointment_pet_id_fkey` (`pet_id` ASC) VISIBLE,
  CONSTRAINT `tbl_appointment_client_id_fkey`
    FOREIGN KEY (`client_id`)
    REFERENCES `db_petsaude`.`tbl_client` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `tbl_appointment_pet_id_fkey`
    FOREIGN KEY (`pet_id`)
    REFERENCES `db_petsaude`.`tbl_pet` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `tbl_appointment_veterinary_id_fkey`
    FOREIGN KEY (`veterinary_id`)
    REFERENCES `db_petsaude`.`tbl_veterinary` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_petsaude`.`tbl_pet_specie_veterinary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_petsaude`.`tbl_pet_specie_veterinary` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pet_specie_id` INT NULL DEFAULT NULL,
  `veterinary_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `tbl_pet_specie_veterinary_pet_specie_id_fkey` (`pet_specie_id` ASC) VISIBLE,
  INDEX `tbl_pet_specie_veterinary_veterinary_id_fkey` (`veterinary_id` ASC) VISIBLE,
  CONSTRAINT `tbl_pet_specie_veterinary_pet_specie_id_fkey`
    FOREIGN KEY (`pet_specie_id`)
    REFERENCES `db_petsaude`.`tbl_pet_specie` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `tbl_pet_specie_veterinary_veterinary_id_fkey`
    FOREIGN KEY (`veterinary_id`)
    REFERENCES `db_petsaude`.`tbl_veterinary` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_petsaude`.`tbl_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_petsaude`.`tbl_post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `text` VARCHAR(1000) NOT NULL,
  `image` VARCHAR(191) NULL DEFAULT NULL,
  `veterinary_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `tbl_post_veterinary_id_fkey` (`veterinary_id` ASC) VISIBLE,
  CONSTRAINT `tbl_post_veterinary_id_fkey`
    FOREIGN KEY (`veterinary_id`)
    REFERENCES `db_petsaude`.`tbl_veterinary` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_petsaude`.`tbl_rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_petsaude`.`tbl_rating` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(200) NOT NULL,
  `score` DECIMAL(2,1) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `veterinary_id` INT NULL DEFAULT NULL,
  `client_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `tbl_rating_veterinary_id_fkey` (`veterinary_id` ASC) VISIBLE,
  INDEX `tbl_rating_client_id_fkey` (`client_id` ASC) VISIBLE,
  CONSTRAINT `tbl_rating_client_id_fkey`
    FOREIGN KEY (`client_id`)
    REFERENCES `db_petsaude`.`tbl_client` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `tbl_rating_veterinary_id_fkey`
    FOREIGN KEY (`veterinary_id`)
    REFERENCES `db_petsaude`.`tbl_veterinary` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_petsaude`.`tbl_specialities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_petsaude`.`tbl_specialities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TINYTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `db_petsaude`.`tbl_veterinary_specialities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_petsaude`.`tbl_veterinary_specialities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `specialities_id` INT NOT NULL,
  `veterinary_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `tbl_veterinary_specialities_specialities_id_fkey` (`specialities_id` ASC) VISIBLE,
  INDEX `tbl_veterinary_specialities_veterinary_id_fkey` (`veterinary_id` ASC) VISIBLE,
  CONSTRAINT `tbl_veterinary_specialities_specialities_id_fkey`
    FOREIGN KEY (`specialities_id`)
    REFERENCES `db_petsaude`.`tbl_specialities` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `tbl_veterinary_specialities_veterinary_id_fkey`
    FOREIGN KEY (`veterinary_id`)
    REFERENCES `db_petsaude`.`tbl_veterinary` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
